name: release
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  code:
    uses: unional/.github/.github/workflows/pnpm-verify.yml@main
    with:
      node-version: '["lts/-1", "lts/*"]'

  release:
    uses: unional/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit

  # docgen:
  #     uses: unional/.github/.github/workflows/pnpm-docs.yml@main
  #     needs: release
